services:
  aegis-api:
    build:
      context: ./aegis
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5001:5001"
    env_file:
      - ./.env
    volumes:
      - ./aegis:/app
    restart: unless-stopped
    networks:
      smartswap-net:
        ipv4_address: 172.28.0.11
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nexus-api:
    build:
      context: ./nexus
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - ./.env
    environment:
      - LOGS_DB_URL=jdbc:clickhouse://logs-database:8123/default
      - LOGS_DB_USERNAME=${CLICKHOUSE_USER}
      - LOGS_DB_PASSWORD=${CLICKHOUSE_PASSWORD}
    restart: unless-stopped
    networks:
      smartswap-net:
        ipv4_address: 172.28.0.12
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - logs-database

  qtb:
    build:
      context: ./qtb
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./qtb/configs:/app/configs
      - ./qtb/logs:/app/logs
      - ./QTSBE/data:/app/QTSBE/data
    restart: unless-stopped
    networks:
      smartswap-net:
        ipv4_address: 172.28.0.10
    ports:
      - "127.0.0.1:5003:5003"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  qtsbe-api:
    build:
      context: ./QTSBE
      dockerfile: Dockerfile
    volumes:
      - ./QTSBE:/app
    command: python api/api.py
    ports:
      - "127.0.0.1:5002:5002"
    env_file:
      - ./.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - smartswap-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  qtsbe-auto-fetch:
    build:
      context: ./QTSBE
      dockerfile: Dockerfile
    volumes:
      - ./QTSBE:/app
    command: python /app/tools/auto_fetch/auto-fetch.py
    env_file:
      - ./.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - smartswap-net
    ports:
      - "127.0.0.1:5004:5004"

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      NODE_ENV: development
    command: >
      sh -c "npm install && npm start"
    networks:
      - smartswap-net

  www:
    build:
      context: ./www
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - smartswap-net

  logs-database:
    image: clickhouse/clickhouse-server:latest
    container_name: logs-database
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_init:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - smartswap-net

volumes:
  clickhouse_data: {}

networks:
  smartswap-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
