services:
  aegis-api:
    build:
      context: ./aegis
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./aegis/.env
    volumes:
      - ./aegis:/app
    restart: unless-stopped
    networks:
      smartswap-net:
        ipv4_address: 172.28.0.11
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  qtb:
    build:
      context: ./qtb
      dockerfile: Dockerfile
    env_file:
      - ./qtb/.env
    volumes:
      - ./qtb/configs:/app/configs
      - ./qtb/logs:/app/logs
    restart: unless-stopped
    networks:
      smartswap-net:
        ipv4_address: 172.28.0.10
    ports:
      - "5003:5003"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  qtsbe-api:
    build:
      context: ./QTSBE
      dockerfile: Dockerfile
    volumes:
      - ./QTSBE:/app
    command: python api/api.py
    ports:
      - "5002:5002"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - smartswap-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  qtsbe-auto-fetch:
    build:
      context: ./QTSBE
      dockerfile: Dockerfile
    volumes:
      - ./QTSBE:/app
    command: python /app/tools/auto_fetch/auto-fetch.py
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: >
      sh -c "npm install && npm start"
    networks:
      - smartswap-net

  www:
    build:
      context: ./www
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - smartswap-net

networks:
  smartswap-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16